---
version: "3"
services:
  postgres:
    image: "postgres:12"
    environment:
      POSTGRES_PASSWORD: test
  phppgadmin:
    build: .
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_NAME: postgres
    ports:
      - 8080:8080
...
